### ISSUE TITLE
Suggestion: Use UUID as ids

### ISSUE THREAD

**Issue by mishoboss** [draedful/websocket-rpc-client#2]
It would be better to use UUIDs instead of plain integers as ids. Most JSON-RPC implementations do this. A simple change is enough:

On ws/pool.js modify the getIndex function to look like this:

```
getIndex: function getIndex() {
        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
           var r = Math.random()*16|0, v = c == 'x' ? r : (r&0x3|0x8);
           return v.toString(16);
        });
    },
```

**Comment by mishoboss** [comment]
P.S. Or even better - make it as config option for users to chose what to use as ids - integers or UUIDs.

**Comment by draedful** [comment]
I thought of such an implementation, but decided it was too time-consuming operation.

**Comment by draedful** [comment]
Is necessary make tests

**Comment by mishoboss** [comment]
It actually is very quick and easy. I just did it and it work well with my json-rpc server.

**Comment by draedful** [comment]
ok. soon realizing this functionality.
